name: Release
on:
  push:
jobs:
  build:
    name: Build Source Code
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: check version change
        id: version
        uses: EndBug/version-check@v2
        with:
          diff-search: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: verify version change
        if: steps.version.outputs.changed == 'false'
        run: 'echo "VERSION CHANGE NOT DETECTED" && exit 1'

      - name: persist version
        run: sed -i 's/_INSPIRETMS_%_____VERSION_____%_INSPIRETMS_/${{ steps.version.outputs.version }}/g' *

      - name: setup
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - run: npm ci

      - name: generate client
        run: npm run types

      - name: build source code
        run: npm run build

      - name: publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.version }}